### ISSUE TITLE
Providing multiple codes for a single Phenotype, Disease, etc.

### ISSUE THREAD

**Issue by RobertJCarroll** [phenopackets/phenopacket-schema#140]
At the GA4GH Connect meeting, we discussed the possibility of providing mappings for codes in phenopackets. One possibility of helping to address this is expanding the OntologyClass item within each Phenotype to allow multiple OntologyClass items representing the "same" phenotype. FHIR allows such arrays of terms, which can allow for cases where multiple assigned concepts are helpful. For example, I've leveraged this to allow locally defined coding in coordination with accepted community standards.

**Comment by julesjacobsen** [comment]
I'm less keen on this idea as the inclusion of multiple codes doesn't specify whether the codes are synonyms or ought to  be logically combined (e.g. left + arm) in the case of underspecified codes. It also adds an enormous amount of extra complexity when dealing with the data - are the codes all present in all cases? What if they're not? Are the codes really synonyms? Are these the same synonyms as those generated by a different method?

The use of a local coding system is perfectly legal and useful, just so long as people know what they are dealing with. These can be converted to a more widely-used system, where required.

Should anyone else be interested in this I'd suggest having a `synonyms` field in order to be specific about the meaning of these other codes.

**Comment by RobertJCarroll** [comment]
Synonyms might be reasonable. What would belong in the main field, eg, local code is primary and the standardized ontology code is the synonym? Is it up to the user? It may encourage individuals adding synonyms, which may be helpful.

**Comment by pnrobinson** [comment]
@RobertJCarroll The phenopacket itself does not mandate the use of any particular ontologies, and so it would be no problem to use local codes. It seems out of scope to have the phenopacket also contain mappings between local and standardized ontology terms, though, this would add complexity and leave more room for error. I would suggest that if a center is using phenopackets with local codes and wants to transmit the data elsewhere, that they map the local codes to the corresponding global codes before doing so.

**Comment by RobertJCarroll** [comment]
Ok, thanks. I wonder if this inherently limits the portability of the phenopackets, as I will now have multiple versions of the same phenopacket for use in different circumstances.
