### ISSUE TITLE
Individual age at collection

### ISSUE THREAD

**Issue by ametke** [phenopackets/phenopacket-schema#161]
The description for an Individual's age_at_collection is the following: "An age object describing the age of the individual at the time of collection _of biospecimens or phenotypic observations_ reported in the current Phenopacket". A Biosample also has an individual_age_at_collection attribute and PhenotypicFeature has an age_of_onset attribute. It seems to me that the age_at_collection attribute in Individual is ambiguous and also redundant. Or am I missing something?

**Comment by julesjacobsen** [comment]
For example we have a patient who is now 25 years old with cancer, global developmental delay and hypotelorism.
Simplifying the syntax for this example.

They are 25 when they are recorded:
Individual.age_at_collection = 25Y

Their global developmental delay and hypotelorism were onset at birth and manifested at a later stage:
hypotelorism.age_of_onset = 0Y
global developmental delay.age_of_onset = 2Y

A tumour biopsy was taken when the patient was 23 years old:
biosample1.individual_age_at_collection = 23Y

and a second one two years later:
biosample2.individual_age_at_collection = 25Y

Does this clarify things?

**Comment by ametke** [comment]
Thanks Jules. I understand what is going on now. I think Individual.age_at_collection is really referring to an encounter with the patient (in FHIR an Encounter is "an interaction during which services are provided to the patient"). You don't have the notion of an "encounter" in the Phenopackets model and that is why this gets pushed into the Individual.

I think there might be some limitations with this approach when exporting Phenopackets at different points in time. Using your example, let's say the patient is now 26Y, develops a new phenotype and you want to export a new Phenopacket. In this case what would the Individual.age_at_collection be? 26Y? If this is the case then you've lost the fact that the hypotelorism and global developmental delay phenotypes were captured when the patient was 25Y.

I am wondering if that age is in fact useful? O maybe you just need the most recent age when information was recorded? If the latter is the case then it should probably be renamed to make things a bit clearer. Otherwise you might want to introduce the notion of an Encounter in the model.

**Comment by julesjacobsen** [comment]
I see your point, but how relevant is it that the hypotelorism and global developmental delay phenotypes were captured when the patient was 25Y when the onset was at birth? It is supposed to be a snapshot of the current status rather than a complete audit so we just need the most recent age when information was recorded, hence the Individual.age_at_collection. 

So in the case that a new observation was made when the patient is now 26Y there would be a new PhenotypicFeature with age_of_onset = 26Y and Individual.age_at_collection = 26Y.

What you suggest renaming the age_at_collection to?

**Comment by ametke** [comment]
I guess I'm still a bit confused about the purpose of the attribute. Is it to know when the snapshot was produced (which I guess would be useful to deal with "deltas")? Or is it to record the age of the patient when the most recent interaction occurred? If it is the latter then maybe age_at_most_recent_encounter? If it is the former then I think it should not be an attribute of Individual.

**Comment by julesjacobsen** [comment]
The Individual.age_at_collection is to record the age of the patient when the most recent interaction occurred. This is because, depending on the requirements of the user, stating the date of birth of the patient may not be allowed so an approximate age or age range can be substituted. If the date of birth is used then there isn't a requirement for `age_at_collection`. There is a MetaData.created to indicate when the snapshot was produced.

See https://phenopackets-schema.readthedocs.io/en/latest/individual.html#date-of-birth for the formal specification.

**Comment by ametke** [comment]
Thanks Jules. It's clear now, but I still think the name is a bit misleading, because the most recent interaction might not necessarily be a collection of biospecimens. I like age_at_most_recent_encounter because it aligns with FHIR terminology but could also be age_at_most_recent_interaction or something along those lines.

**Comment by pnrobinson** [comment]
@ametke hope you can join the GA4GH meeting tomorrow to discuss some of the issues. 
The age_at_most_recent_encounter suggestion seems sensible, although it would be a breaking change. @julesjacobsen , thoughts?

**Comment by pnrobinson** [comment]
@julesjacobsen given that there will be a few breaking changes in v2, I would support the suggestion of @ametke to use the term ``age_at_most_recent_encounter``, which is much more evocative (to me) that ``age_at_collection`` (which has no meaning to me outside of our current usage in phenopackets).

**Comment by julesjacobsen** [comment]
We decided to rename the element to `age_at_encounter`. Note this is now a `TimeElement`, but this might need to be narrowed down to only include one of `Age`, `AgeRange` or `GestationalAge` as a `TimeElement` also includes `Timestamp` and `TimeInterval` which are not appropriate here.

```proto
    TimeElement age_at_encounter = 11;
}
```

@ametke does this make sense to you?

**Comment by ametke** [comment]
Sounds good @julesjacobsen.

**Comment by pnrobinson** [comment]
super, thanks @ametke, closing
