### ISSUE TITLE
Resource.html

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#191]
Bob F.'s comment
```
The descriptions in this class refer heavily to its use to describe ontologies.  
Please add more guidance for non-ontologies. If specific requirements are imposed 
for ontologies, perhaps a “type” field (and value set) should be added so those 
instances can be computationally identified.  This would be the equivalent of subclassing 
Resource to OntologyResource.
```

@cmungall @mellybelly @julesjacobsen Thoughts?

**Comment by julesjacobsen** [comment]
This is the _**final**_ issue to respond to @cmungall, if you have any thoughts on this it would be good to hear them.

The page in question is this:

https://phenopackets-schema.readthedocs.io/en/latest/resource.html

I can only say that this only applies to curie-based identifiers, which should be all cases of OntologyClass.id, but could potentially be any other id, e.g. an HGNC identifier.

The question is whether ontology resources should be treated differently to other resources. I think probably not.

For example, here is an ontology resource:

```json
{
    "id": "so",
    "name": "Sequence types and features",
    "url": "http://purl.obolibrary.org/obo/so.owl",
    "version": "2015-11-24",
    "namespacePrefix": "SO",
    "iriPrefix": "http://purl.obolibrary.org/obo/SO_"
}
```
and here is the HGNC. Being a locatable resource the iriPrefix is present. e.g. `HGNC:12805`
```json
{
    "id": "hgnc",
    "name": "HUGO Gene Nomenclature Committee",
    "url": "https://www.genenames.org",
    "version": "2019-08-08",
    "namespacePrefix": "HGNC",
    "iriPrefix": "https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/"
}
```
or for UniProtKB e.g. identifier `UNIPROT:Q8H0D3`
```json
{
    "id": "uniprot",
    "name": "The Universal Protein Resource",
    "url": "https://www.uniprot.org",
    "version": "2019_07",
    "namespacePrefix": "UNIPROT",
    "iriPrefix": "https://purl.uniprot.org/uniprot/"
}
```
So I think the real issue is having to test each and every identifier, outside of an OntologyClass, to see if it is a CURIE and whether or not it is locatable, but this might not matter in all cases.

**Comment by cmungall** [comment]
I agree, makes sense to treat all IDs the same

minor: I might try and align the URL expansions with dipper prefixes.yaml
which we are also trying to align with GO. We use identifiers.org for gene
databases in GO
