### ISSUE TITLE
Proposed addition to VcfAllele element

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-schema#211]
I have noticed that the current Phenopacket format is not able to deal with this kind of structural variant call in a VCF file
```
4 18665128  . T <DUP:TANDEM>  11  PASS  IMPRECISE;SVTYPE=DUP;END=18665204;SVLEN=76;CIPOS=-10,10;CIEND=-10,10  GT:GQ:CN:CNQ  ./.:0:5:8.3
```
In the current format, we allow the INFO field (which starts with 'IMPRECISE' here) to be entered, but not the GENOTYPE (``GT:GQ:CN:CNQ``) or SAMPLE fields (``./.:0:5:8.3``). In the current case, no  genotype call is being made ``(./.)`` so in the current format, we can only use the GENO term _unspecified zygosity_.  In this case, the ``CN`` in the genotype field means copy number. So the VCF line means that there is a copy number total of 5 but we do not know the genotype. 

We can solve this by either allowing users to enter both a genotype field and sample field or perhaps by adding a field called "CopyNumber" to the VcfAllele element.

Thoughts?

**Comment by julesjacobsen** [comment]
So we could add the copy_number variable to the Variant message as an optional field, primarily for use when the zygosity is unknown. 
```proto
message Variant {
    oneof allele {
        HgvsAllele hgvs_allele = 2;
        VcfAllele vcf_allele = 3;
        SpdiAllele spdi_allele = 4;
        IscnAllele iscn_allele = 5;
    }
    // Zygosity of the allele using GENO ontology
    OntologyClass zygosity = 6;
    // copy number of the variant mostly useful for when the zygosity is unknown. Optional.
    int32 copy_number = 7;
}
```

**Comment by pnrobinson** [comment]
Still to do -- add this example to the Read the docs!

**Comment by ahwagner** [comment]
This is a tough one. We're still working out this concept (we call them unlocated CNVs) in VR-spec; all I can say clearly is that it wouldn't be of type `Allele`, defined in VR-spec as:
> An Allele is a specific, single, and contiguous Sequence at a Location (Abstract Class). Each alternative Sequence may be empty, shorter, longer, or the same length as the interval (e.g., due to one or more indels).
**DISCLAIMER:** I won't say more about where VR spec is going, because that's a larger discussion that hasn't matured much since our push to get v1.0 out. I also don't want my own notions on this subject (following) to be considered representative of the plans of the VR group in any way.
As to how to model the CNVs in Phenopackets, I think of it as a standalone structure, such as the following:

```protobuf
message CNV {
    message LocatedAllele {
        oneof allele {
            HgvsAllele hgvs_allele = 1;
            VcfAllele vcf_allele = 2;
            SpdiAllele spdi_allele = 3;
            IscnAllele iscn_allele = 4;
            Ga4ghAllele ga4gh_allele = 5;
        }
        optional Ga4ghLocation destination = 6;
    }
    repeated Translocation = 1;
}
```
In this way, you can explicitly describe all instances of one or more repeated alleles constituting a CNV as a set of `LocatedAllele` objects (there might be a better name for this, though _translocation_ doesn't feel right if one or more of these objects is in the native/expected location).  The optional `destination` if left empty allows for unlocated CNVs, but if filled designates a location that is replaced with the allele. Does this capture the above use case?

(Please forgive the almost certainly bad syntax above–I am new at writing protobuf) 

Also, tagging @reece, @larrybabb, and @rrfreimuth, who are probably just as keen to provide input on how this could be handled in Phenopackets.

**Comment by julesjacobsen** [comment]
Thank for the valuable input @ahwagner. This is clearly entering into the realms of VR spec and will take time to model properly so I vote for moving this to a future version as this is currently blocking the release of 1.0.0.

**Comment by pnrobinson** [comment]
@julesjacobsen we need to think about this element for v2. This is currently one of the blockers for our SV software that uses phenopackets, and so it might also be a general need.

**Comment by pnrobinson** [comment]
@julesjacobsen I think these changes address the issue, so I will close. We can reopen if there are any additional thoughts.
