### ISSUE TITLE
Incorporating VRS into Phenopackets

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#219]
@pnrobinson @larrybabb @reece I went with the 'full' implementation approach as we agreed would be worth trying. I implemented the VR spec using its own namespace so the proto was something like this:

```proto
message Text {
    // The computed CURIE for this object
    string _id = 1;
    string definition = 2;
    // MUST be the value 'Text'
    string type = 3;
}

message Allele {
    // The computed CURIE for this object
    string _id = 1;
    SequenceLocation location = 2;
    SequenceState state = 3;
    // MUST be the value 'Allele'
    string type = 4;
}

message SequenceLocation {
    // The computed CURIE for this object
    string _id = 1;
    SimpleInterval interval = 2;
    // A CURIE identifier for the sequence
    string sequence_id = 3;
    // MUST be the value 'SequenceLocation'
    string type = 4;
}

message SimpleInterval {
    // The computed CURIE for this object
    string _id = 1;
    uint64 end = 2;
    uint64 start = 3;
    // MUST be the value 'SequenceLocation'
    string type = 4;
}

message SequenceState {
    // The computed CURIE for this object
    string _id = 1;
    string sequence = 2;
    // MUST be the value 'SequenceState'
    string type = 3;
}
```

Thanks to the lack of inheritance and the weird way protobuf implements enums it wasn't quite as elegant as I'd have liked. This meant I had to use a string rather than an enum for the type field and the Allele, SequenceLocation and SequenceState use the specific rather than generic type (i.e. Location and State). Will this be an issue? If so this is definitely a blocker and we'll have to go with @reece 's initial suggestion, which I rudely shot down (sorry, didn't intend to be rude, merely enthusiastic to fully-support!) and simply go with the JSON string representation of the VRS Variation.    

Anyway this is the end result:

```proto
message Variant {
    oneof allele {
        HgvsAllele hgvs_allele = 2;
        VcfAllele vcf_allele = 3;
        SpdiAllele spdi_allele = 4;
        IscnAllele iscn_allele = 5;
        org.ga4gh.vrs.v1.Allele vrs_allele = 7;
    }
    // Zygosity of the allele using GENO ontology
    OntologyClass zygosity = 6;
}
```

Here's the rare disease Pfeiffer example using a VRS Allele message

```json
{
  "subject": {
    "id": "proband",
    "sex": "MALE"
  },
  "phenotypicFeatures": [{
    "type": {
      "id": "HP:0001156",
      "label": "Brachydactyly"
    }
  }],
  "genes": [{
    "id": "HGNC:3689",
    "symbol": "FGFR2"
  }],
  "variants": [{
    "zygosity": {
      "id": "GENO:0000135",
      "label": "heterozygous"
    },
    "vrsAllele": {
      "location": {
        "interval": {
          "end": "123256215",
          "start": "123256214",
          "type": "SimpleInterval"
        },
        "sequenceId": "refseq:NC_000010.10",
        "type": "SequenceLocation"
      },
      "state": {
        "sequence": "G",
        "type": "SequenceState"
      },
      "type": "Allele"
    }
  }],
  "diseases": [{
    "term": {
      "id": "OMIM:101600",
      "label": "PFEIFFER SYNDROME"
    }
  }],
  "htsFiles": [{
    "uri": "file://data/vcfs/proband.vcf",
    "htsFormat": "VCF",
    "genomeAssembly": "GRCh37",
    "individualToSampleIdentifiers": {
      "proband": "SAMPLE0001"
    }
  }]
}
```

**Comment by pnrobinson** [comment]
Just for my own edification, the purpose of the "field" elements is not actually for the protobuf implementation but to support inheritance type operations in the JSON? Not sure I follow.

**Comment by julesjacobsen** [comment]
You mean the "type" field/elements e.g. `"type": "Allele"`? Yes, these are purely to support the JSON inheritance. It does seem out of place in here and it's more of artefact of the inheritance model than a requirement of the actual spec.

Would make more sense like this:

```json
  "vrsAllele": {
      "location": {
        "interval": {
          "end": "123256215",
          "start": "123256214",
        },
        "sequenceId": "refseq:NC_000010.10",
      },
      "state": {
        "sequence": "G",
      }
    }
```

**Comment by larrybabb** [comment]
@julesjacobsen I will defer to @reece for the initial questions in your post at the start of this issue. 

As far as your question directly above

The `type` fields and their values `Allele, SequenceLocation, SimpleInterval,...` are required and contribute to the computed identifiers. Without them I'm fairly certain we wouldn't consider the structure to be compliant with the standard.

**Comment by reece** [comment]
Hi @julesjacobsen . So sorry for having forgotten to reply. Thanks to Lindsay for the the prod!

I think you've actually got two questions there. You wrote (with my annotations in square brackets): 

> This meant I had to ① [use a string rather than an enum for the type field] and
> ② [the Allele, SequenceLocation and SequenceState use the specific rather than generic type
> (i.e. Location and State). Will this be an issue?

① The type field (called the discriminator in this context) is the way that JSON schema discriminates between subclasses of a parent. Without the discriminator, JSON schema can't know the object type.  It is strictly required for the JSON form. Type is fundamentally a string, even though it's implemented as an enum of strings in the schema. So, if you can get the right string into the type attribute of the JSON representation, you will be fine.

Protobuf has a different way of tracking message types (built into the protocol itself), and I definitely think that you should use that. You will have to figure out how to inject the type attribute into the message when it's realized as JSON.

② By ditching the inheritance component, you'll be limiting your implementation to a subset of functionality. Furthermore, it will surely mean that the protobuf implementation drifts further and further out of meaningful support for VRS as VRS evolves. It is not appealing that your system will fail with perfectly valid VRS messages because certain functionality isn't supported. I'm not sure that we would consider this a valid implementation.

If phenopackets were not affiliated with GA4GH, I think my initial opinion is that I'm not happy about it, but that I'd cheer on the parts that you did support rather than bemoan the gaps.

However, given that phenopackets is is a GA4GH project, it should meet a higher bar for compatibility with other GA4GH standards. Implementing a partial (or, worse, erroneous) standard ultimately undermines the organization's mission.

These are my opinions. I don't really have any power to stop you from doing anything. I do expect that the review process would raise similar concerns.


@larrybabb @rfreimuth

**Comment by julesjacobsen** [comment]
The VRS 1.2rc spec is implemented in https://github.com/phenopackets/phenopacket-schema/tree/vrs

This 'works' and produces valid JSON according to a schema validator validating against the VRS JSON schema (https://www.jsonschemavalidator.net/s/DfLEG3Gs), however there are a lot of 'intermediate' classes present due to the way protobuf handles 'oneof's.

for example the JSON output from the protobuf model is:

```json
{
  "type": "Allele",
  "location": {
    "sequence_location": {
      "type": "SequenceLocation",
      "sequence_id": "ga4gh:SQ.IIB53T8CNeJJdUqzn9V_JnRtQadwWCbl",
      "interval": {
        "simple_interval": {
          "type": "SimpleInterval",
          "start": "44908822",
          "end": "44908821"
        }
      }
    }
  },
  "sequence_expression": {
    "literal": {
      "type": "LiteralSequenceExpression",
      "sequence": "T"
    }
  }
}
```
  
and from the VRS 1.2rc docs for [allele](https://vrs.ga4gh.org/en/1.2.0.rc0/terms_and_model.html#allele):

```json
{
   "location": {
      "interval": {
         "end": 44908822,
         "start": 44908821,
         "type": "SimpleInterval"
      },
      "sequence_id": "ga4gh:SQ.IIB53T8CNeJJdUqzn9V_JnRtQadwWCbl",
      "type": "SequenceLocation"
   },
   "state": {
      "sequence": "T",
      "type": "LiteralSequenceExpression"
   },
   "type": "Allele"
}
```

Does this still work?!

**Comment by reece** [comment]
No, that's not valid.

I don't know why the validator accepts that message.

The schema that you pointed to has (edited):

```
      "SequenceLocation": {
         "additionalProperties": false,
         "description": "A specified subsequence within another sequence that is used as a reference sequence.",
         "properties": {
            "_id": { ... },
            "interval": { "$ref": "#/definitions/SequenceInterval" },
            "sequence_id": { ... },
            "type": { ... }
         },
         "type": "object"
      },
```
`additionalProperties = false` should mean that any property not listed in `properties` would cause an error. In particular, the `sequence_location` generated by protobuf is not permitted.

A similar problem exists with the `simple_interval` attribute.

I haven't dealt with protobuf in at least 3 years. However, the modeling by composition used by protobuf is going to create a fundamentally different structure that that used by JSON Schema. I don't see how protobuf and JSON Schema inheritance/composition will ever magically resolve in the way you're seeking.

@larrybabb @ahwagner

**Comment by ahwagner** [comment]
The reason that was happening is that the JSON Schema document @julesjacobsen is using are the definitions only. The schema validator loads the definitions but is otherwise unconstrained. Literally any valid JSON will verify in the above example, e.g. https://www.jsonschemavalidator.net/s/SVSpF4aB.

To make this actually validate against the definitions, you need to add a constraint for the object type you are expecting (as you would do in implementation) such as "$ref": "#/definitions/Allele" after the definitions, e.g. https://www.jsonschemavalidator.net/s/qCVtP9Df. As @reece knows, the VRS schema.json was intentionally designed this way to allow its use in a variety of settings where the various VRS components may be interwoven in a larger JSON Schema.

I am interested in making these GA4GH standards work together, and am consequently working on getting a compatible (though not equivalent) protobuf implementation for use by the Phenopackets team. This is slow going due to my inexperience in Protobuf, but this appears to be the shortest gap at which to span the divide.

**Comment by reece** [comment]
Ah, yes, @ahwagner is right. The top-level object is unconstrained, so it would take anything.

I remain unclear how protobuf's inheritance by composition can ever be made consistent with JSON Schema's inheritance with a discriminator. Protobuf's approach necessitates a nested/wrapping object that won't exist in JSON Schema's representation. Obviously, it's code, so anything is possible, but this problem seems especially tricky.

**Comment by julesjacobsen** [comment]
@ahwagner did you see this file?

https://github.com/phenopackets/phenopacket-schema/blob/vrs/src/main/proto/vrs.proto

It contains the VSR 1.2rc spec in proto format. 

This is a simple allele test file:

https://github.com/phenopackets/phenopacket-schema/blob/vrs/src/test/java/org/ga4gh/vrs/v1/VrsTest.java

**Comment by julesjacobsen** [comment]
@reece @ahwagner I can't see any simple and seamless way to reconcile the technical differences between protobuf and JSON schema, but maybe there isn't an absolute requirement to be able to do this?

The phenopacket version of VRS aka 'phenovrs' does use identical field names and has the same logical structure (minus inheritance) such that it should be possible for a system to receive a phenopacket message and translate it into a VRS variation. Alternatively they can just use the phenovrs as-is and use the VRS model of variation, which is still useful in its own right. 

Is it still possible to generate the VRS hash correctly though?

How useable is the proto version? 

Have I correctly interpreted your schema?

**Comment by julesjacobsen** [comment]
done 9474e94933b0b4705d262cb9c8dc75eb4b52e1ad thank to @ahwagner and the rest of the VRS team
